apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "global-azure-2022-chart.fullname" . }}
  labels:
    {{- include "global-azure-2022-chart.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "global-azure-2022-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "global-azure-2022-chart.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "global-azure-2022-chart.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: {{.Values.configMap.name }}
          configMap:
            name: {{.Values.configMap.name }}-file
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: JAVA_OPTS
              value: {{.Values.container.env.JAVA_OPTS }}
            - name: APPLICATIONINSIGHTS_CONNECTION_STRING
              value: {{.Values.container.env.APPLICATIONINSIGHTS_CONNECTION_STRING }}
            - name: spring.config.additional-location
              value: {{.Values.container.env.SPRING_CONFIG_ADDITIONAL_LOCATION }}
          ports:
            - name: http
              containerPort: 9090
              protocol: TCP
          volumeMounts:
            - name: {{.Values.configMap.name }}
              mountPath: /globalAzure2022/storage
          livenessProbe:
            httpGet:
              path: {{ .Values.probs.livenessProbe.path }}
              port: http
          readinessProbe:
            httpGet:
              path: {{ .Values.probs.readinessProbe.path }}
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
