server:
  port: 9090
  error:
    include-message: always
    include-exception: true
springdoc:
  swagger-ui:
    path: /globalazure-api.html
post:
  base-url: https://jsonplaceholder.typicode.com
  url-get-all: ${post.base-url}/posts
spring:
  cloud:
    loadbalancer:
      ribbon:
        enable: false
  config:
    import: "classpath:application-private.yaml"  # This file hosts the private keys and never pushed to the remote repository